customers/urls.py
from django.urls import path

from .api.views import discount_code_view
from .views import orders_history_view, profile_view, recent_orders_view

urlpatterns = [
    path("profile/", profile_view, name="profile"),
    path("orders/", orders_history_view, name="orders"),
    path("orders/recent/", recent_orders_view, name="recent_orders"),
    path("rest/discount-code/", discount_code_view, name="discount_code"),
]

django_ecommerce/urls.py
from allauth.account.views import confirm_email
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls")),  # our main page will be in products app.
    path("customer/", include("customers.urls")),
    path("order/", include("orders.urls")),
    url(r"^rest-auth/", include("rest_auth.urls")),
    url(r"^rest-auth/registration/", include("rest_auth.registration.urls")),
    url(r"^account/", include("allauth.urls")),
    url(
        r"^accounts-rest/registration/account-confirm-email/(?P<key>.+)/$",
        confirm_email,
        name="account_confirm_email",
    ),
]

orders/urls.py
from django.urls import path

from .api.views import update_session
from .views import (add_to_basket, basket_view, checkout, create_order,
                    delete_address, delete_from_basket)

urlpatterns = [
    path("basket/", basket_view, name="basket"),
    path("add-to-basket/", add_to_basket, name="add_to_basket"),
    path(
        "delete-from-basket/<int:product_id>/",
        delete_from_basket,
        name="delete_from_basket",
    ),
    path("checkout/", checkout, name="checkout"),
    path("delete-address/<int:address_id>/", delete_address, name="delete_address"),
    path("checkout/create-order/", create_order, name="create_order"),
    path("update-session/", update_session, name="update_session"),
]

customers/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField

from .managers import CustomUserManager


def validate_only_one_instance(obj):
    model = obj.__class__
    print(obj.user)
    if model.objects.filter(user=obj.user).count() > 1:
        raise ValidationError(
            "Can only create 2 %s instance with same user" % model.__name__
        )


class Customer(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    phone = PhoneNumberField(null=False, blank=False)

    MALE = False
    FEMALE = True
    gender_type = ((MALE, "مرد"), (FEMALE, "زن"))
    gender = models.BooleanField(
        default=True, choices=gender_type, null=False, blank=False
    )

    def __str__(self):
        return self.email


class Address(models.Model):
    user = models.ForeignKey(
        Customer, on_delete=models.CASCADE, blank=False, null=False
    )
    province = models.CharField(max_length=100, blank=False, null=False)
    city = models.CharField(max_length=100, blank=False, null=False)
    postcode = models.CharField(max_length=12, blank=False, null=False)
    address = models.CharField(max_length=1200, blank=False, null=False)

    def __str__(self):
        return self.user.email

    def clean(self):
        validate_only_one_instance(self)

    class Meta:
        verbose_name_plural = "Addresses"


class DiscountCode(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    code = models.CharField(max_length=10, unique=True)
    amount = models.PositiveIntegerField()
    start_date = models.DateTimeField()
    expire_date = models.DateTimeField()

    def __str__(self):
        return str(self.amount) + "%"

customers/forms.py
from allauth.account.forms import ChangePasswordForm, SignupForm
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import Address, Customer


class CustomSignupForm(SignupForm):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    phone = forms.CharField(max_length=15)

    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields["email"].label = "ایمیل"
        self.fields["first_name"].label = "نام"
        self.fields["last_name"].label = "نام خانوادگی"
        self.fields["phone"].label = "شماره تماس"
        # self.fields['gender'].label = 'جنسیت'
        self.fields["password1"].label = "رمز عبور"
        self.fields["password2"].label = "تکرار رمز عبور"

        self.fields["email"].widget.attrs.update({"dir": "ltr"})
        self.fields["password1"].widget.attrs.update({"placeholder": "رمز عبور"})
        self.fields["password2"].widget.attrs.update({"placeholder": "تکرار رمز عبور"})
        self.fields["phone"].widget.attrs.update(
            {"placeholder": "+98xxxxxxxxxx", "dir": "ltr"}
        )

    def signup(self, request, user):
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.phone = self.cleaned_data["phone"]
        user.save()
        return user


class DetailForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Customer
        fields = ("email", "first_name", "last_name", "phone", "gender")
        labels = {
            "email": "ایمیل",
            "first_name": "نام",
            "last_name": "نام خانوادگی",
            "phone": "شماره تماس",
            "gender": "جنسیت",
        }
        widgets = {
            "email": forms.TextInput(
                attrs={"placeholder": "Email", "dir": "ltr", "type": "email"}
            ),
            "phone": forms.TextInput(attrs={"placeholder": "Phone", "dir": "ltr"}),
        }


class CustomChangePasswordForm(ChangePasswordForm):
    def __init__(self, *args, **kwargs):
        super(CustomChangePasswordForm, self).__init__(*args, **kwargs)
        self.fields.pop("oldpassword")
        self.fields["password1"].label = "گذرواژه جدید"
        self.fields["password2"].label = "تکرار گذرواژه جدید"

        self.fields["password1"].widget.attrs.update({"placeholder": "گذرواژه جدید"})
        self.fields["password2"].widget.attrs.update(
            {"placeholder": "تکرار گذرواژه جدید"}
        )


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = "__all__"
        labels = {
            "province": "استان",
            "city": "شهر",
            "postcode": "کد پستی",
            "address": "نشانی   ",
        }
        widgets = {
            "user": forms.HiddenInput(),
        }

customers/api/views.py
from datetime import datetime

import pytz
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from customers.models import DiscountCode

from .serializers import DiscountCodeSerializer

utc = pytz.UTC


@api_view(
    [
        "GET",
    ]
)
def discount_code_view(request):
    if request.user.is_authenticated:

        code = request.query_params.get("code")
        if code is not None:
            query_set = DiscountCode.objects.all().filter(user=request.user, code=code)

            serializer = DiscountCodeSerializer(query_set, many=True)

            # check if query_set is not empty.
            if query_set:
                # check if discount code has expired.
                if utc.localize(datetime.now()) > query_set.first().expire_date:
                    return Response(
                        {"error": "Sorry, your discount code has expired!"},
                        status=status.HTTP_406_NOT_ACCEPTABLE,
                    )

                # if discount code was valid, save it in session.
                request.session["discount"] = {
                    code: query_set.first().amount,
                }
            return Response(serializer.data, status=status.HTTP_200_OK)

        return Response(status=status.HTTP_400_BAD_REQUEST)

    return Response(
        {"error": "لطفا ایتدا وارد اکانت خود شوید."},
        status=status.HTTP_406_NOT_ACCEPTABLE,
    )

customers/views.py
from datetime import date, datetime, timedelta

from django.shortcuts import redirect, render
from django.urls import reverse

from orders.models import Order

from .forms import DetailForm


def profile_view(request):
    if request.user.is_authenticated:

        form = DetailForm(instance=request.user)

        context = {
            "form": form,
        }
        return render(request, "profile.html", context)

    return redirect(reverse("account_login"))


def orders_history_view(request):
    if request.user.is_authenticated:

        orders = Order.objects.filter(user__email=request.user).all()

        context = {
            "orders": orders,
        }
        return render(request, "orders_history.html", context)

    return redirect(reverse("account_login"))


def recent_orders_view(request):
    if request.user.is_authenticated:

        # orders in past 10 days
        recent_orders = Order.objects.filter(
            order_date__range=(datetime.now() - timedelta(days=10), datetime.now()),
            user__email=request.user,
        ).all()

        context = {
            "recent_orders": recent_orders,
        }
        return render(request, "recent_orders.html", context)

    return redirect(reverse("account_login"))

customers/templates/orders_history.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block title %}Orders{% endblock %}

{% block Bootstrap %}
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard-rtl/">
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.rtl.min.css" rel="stylesheet" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.0/examples/dashboard/dashboard.rtl.css" rel="stylesheet">

{% endblock %}

{% block style %}
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    h2 {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    input {
        margin-bottom:20px;
        margin-top: 3px;
    }

    .content {
        text-align: center;
    }

    form {
        display: inline-block;
    }

    #id_gender {
        margin-bottom: 15px;
    }

    .card{
    margin-bottom: 15px;
    }

{% endblock %}

{% block content %}

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">بازار</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="عرض/إخفاء لوحة التنقل">
    <span class="navbar-toggler-icon"></span>
  </button>

</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'profile' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
                  <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
                </svg>
               مشخصات فردی
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_set_password' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shield-lock" viewBox="0 0 16 16">
                  <path d="M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z"/>
                  <path d="M9.5 6.5a1.5 1.5 0 0 1-1 1.415l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99a1.5 1.5 0 1 1 2-1.415z"/>
                </svg>
              حساب کاربری
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'orders' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                  <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                  <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                </svg>
              تاریخچه سفارش ها
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recent_orders' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                  <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                  <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                </svg>
              سفارشات اخیر
            </a>
          </li>
        </ul>

      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

      <h2>تاریخچه سفارش ها</h2>

      <div class="content">
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th scope="col">کد پیگیری</th>
                  <th scope="col">تاریخ</th>
                  <th scope="col">جمع قیمت</th>
                  <th scope="col">وضعیت ارسال</th>
                  <th scope="col">جزئیات</th>
                </tr>
              </thead>
              <tbody>
              {% for order in orders %}
                <tr>
                  <td>{{ order.ref_code }}</td>
                  <td dir="ltr">{{ order.order_date|date:"Y-m-d H:i" }}</td>
                  <td>{{ order.total_price }} تومان</td>
                  <td>{{ order.delivery_status }}</td>
                  <td><a href="#" data-bs-toggle="modal" data-bs-target="#i{{ order.ref_code }}">نمایش</a></td>

                <div class="modal fade" id="i{{ order.ref_code }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">لیست محصولات</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                      <div class="row">
                        {% for product in order.products.all %}

                                  <div class="col-6">
                                    <div class="card text-center">
                                      <a href="{% url 'single_product' product.item.slug %}"><img src="/{{ product.item.image.first.image }}" class="card-img-top" alt="product image"></a>
                                      <div class="card-body">
                                        <h5 class="card-title">{{ product.item.title }}</h5>
                                        <p class="card-text">{{ product.item.description }}</p>
                                      </div>
                                    </div>
                                  </div>

                        {% endfor %}
                      </div>

                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">بستن</button>
                      </div>
                    </div>
                  </div>
                </div>

                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>

      </div>

    </main>
  </div>
</div>

{% endblock %}

{% block js %}<script src="{% static 'js/profile.js' %}"></script>{% endblock %}

customers/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% bootstrap_messages %}

{% block title %}Profile{% endblock %}

{% block Bootstrap %}
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/dashboard-rtl/">
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.rtl.min.css" rel="stylesheet" integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.0/examples/dashboard/dashboard.rtl.css" rel="stylesheet">

{% endblock %}

{% block style %}
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

    h2 {
        margin-top: 20px;
    }

    input {
        margin-bottom:20px;
        margin-top: 3px;
    }

    .content {
        text-align: center;
    }

    form {
        display: inline-block;
    }

    #id_gender {
        margin-bottom: 15px;
    }
{% endblock %}

{% block content %}

<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">بازار</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="عرض/إخفاء لوحة التنقل">
    <span class="navbar-toggler-icon"></span>
  </button>

</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
                  <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816zM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275zM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4z"/>
                </svg>
               مشخصات فردی
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_set_password' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shield-lock" viewBox="0 0 16 16">
                  <path d="M5.338 1.59a61.44 61.44 0 0 0-2.837.856.481.481 0 0 0-.328.39c-.554 4.157.726 7.19 2.253 9.188a10.725 10.725 0 0 0 2.287 2.233c.346.244.652.42.893.533.12.057.218.095.293.118a.55.55 0 0 0 .101.025.615.615 0 0 0 .1-.025c.076-.023.174-.061.294-.118.24-.113.547-.29.893-.533a10.726 10.726 0 0 0 2.287-2.233c1.527-1.997 2.807-5.031 2.253-9.188a.48.48 0 0 0-.328-.39c-.651-.213-1.75-.56-2.837-.855C9.552 1.29 8.531 1.067 8 1.067c-.53 0-1.552.223-2.662.524zM5.072.56C6.157.265 7.31 0 8 0s1.843.265 2.928.56c1.11.3 2.229.655 2.887.87a1.54 1.54 0 0 1 1.044 1.262c.596 4.477-.787 7.795-2.465 9.99a11.775 11.775 0 0 1-2.517 2.453 7.159 7.159 0 0 1-1.048.625c-.28.132-.581.24-.829.24s-.548-.108-.829-.24a7.158 7.158 0 0 1-1.048-.625 11.777 11.777 0 0 1-2.517-2.453C1.928 10.487.545 7.169 1.141 2.692A1.54 1.54 0 0 1 2.185 1.43 62.456 62.456 0 0 1 5.072.56z"/>
                  <path d="M9.5 6.5a1.5 1.5 0 0 1-1 1.415l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99a1.5 1.5 0 1 1 2-1.415z"/>
                </svg>
              حساب کاربری
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'orders' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                  <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                  <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                </svg>
              تاریخچه سفارش ها
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recent_orders' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-text" viewBox="0 0 16 16">
                  <path d="M5.5 7a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5zM5 9.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5z"/>
                  <path d="M9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.5L9.5 0zm0 1v2A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5z"/>
                </svg>
              سفارشات اخیر
            </a>
          </li>
        </ul>

      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">

      <h2>مشخصات فردی</h2>

      <div class="content">
        <form class="form-horizontal" id="details" dir="rtl">
            {% csrf_token %}

            <fieldset id="myFieldset" disabled="disabled">
                {% bootstrap_form form %}
            </fieldset>

            <button type="button" class="btn btn-dark" id="edit" onclick="return handleEdit()">ویرایش</button>
            <button type="button" class="btn btn-dark" id="cancel" onclick="return handleSaveCancel()" hidden>انصراف</button>
            <button type="submit" class="btn btn-dark" id="save" hidden>ذخیره</button>

        </form>
      </div>

    </main>
  </div>
</div>

{% endblock %}

{% block js %}<script src="{% static 'js/profile.js' %}"></script>{% endblock %}